apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-tj2t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-tj2t
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-tj2t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-tj2t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-tj2t
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cbni-tenant/nodejs-users/simple-nodejs-app-tj2t@sha256:ca3f1046731349a3216633ddac58597ff7db4e5a30e74cd20970add058d2486c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
